;; -*- no-byte-compile: t; -*-
;;; .doom.d/packages.el

;;; Examples:
;; (package! some-package)
;; (package! another-package :recipe (:host github :repo "username/repo"))
;; (package! builtin-package :disable t)
(package! wttrin :recipe (:host github :repo "bcbcarl/emacs-wttrin"))
(package! doom-themes)
(package! py-autopep8)
(package! elpy)
(package! org-bullets)
(package! org-super-agenda)
(package! moe-theme)
(package! all-the-icons)
(package! powerline)
(package! hc-zenburn-theme)
(package! avy)
(package! go-autocomplete)
(package! go-playground)
(package! emmet-mode)
(package! tern)
(package! tern-auto-complete)
(package! helm-css-scss)
(package! helm-emmet)
(package! helm-go-package)
(package! go-guru)
(package! go-snippets)
(package! go)
(package! go-imports)
(package! go-eldoc)
(package! js2-mode)
(package! js2-refactor)
(package! flymake-jslint)
(package! pacmacs)
(package! minesweeper)
(package! treemacs-icons-dired)
(package! treemacs-magit)
(package! treemacs-projectile)
